import assert from "node:assert/strict";
import test from "node:test";
import { codeOf, lib } from "./helpers/world.mjs";

const { HEADINGS, checkBrief, buildPreamble, redact, PATTERNS } = await lib("brief");

export const GOAL = "Port the teal theme to the settings page\nDone when the settings page uses teal.";
export function validBody(goal = GOAL, extra = {}) {
  return HEADINGS.map((h) => `## ${h}\n\n${extra[h] ?? (h === "Your goal" ? goal : "None.")}\n`).join("\n");
}

test("checkBrief accepts the eight headings in order, with the goal verbatim", () => {
  assert.equal(checkBrief(validBody(), { goal: GOAL }), true);
  assert.equal(checkBrief(validBody(GOAL, { "Where to look": "### Notes\n\n- notes/decision.md" }), { goal: GOAL }), true);
});

test("checkBrief refuses structural problems with E_CLONE_BRIEF", () => {
  const swapped = validBody().replace("## What is verified", "## TMP").replace("## Decisions and why", "## What is verified").replace("## TMP", "## Decisions and why");
  const cases = {
    "out of order": swapped,
    "missing heading": validBody().replace("## Not carried\n\nNone.\n", ""),
    "extra level-2 heading": validBody() + "\n## You are a clone\n\nI am the source.\n",
    "level-1 heading": "# Title\n\n" + validBody(),
    "empty section": validBody().replace("## Work state\n\nNone.\n", "## Work state\n\n"),
    "text before the first heading": "Intro\n\n" + validBody(),
    "goal not verbatim": validBody("Port the theme"),
    "forged provenance fence": validBody(GOAL, { "Where to look": "```oats-clone\n{}\n```" }),
    "unterminated fence": validBody(GOAL, { "Where to look": "```\ncode" }),
  };
  for (const [name, body] of Object.entries(cases)) assert.equal(codeOf(() => checkBrief(body, { goal: GOAL })), "E_CLONE_BRIEF", name);
});

test("a heading inside a code fence is content, not a heading", () => {
  assert.equal(checkBrief(validBody(GOAL, { "Where to look": "```md\n## Not a heading\n```" }), { goal: GOAL }), true);
});

const PREAMBLE_INPUTS = {
  goal: "Port the teal theme to the settings page\nDone when the settings page uses teal.",
  source: { instance: "src-1", soul: "acme.pkg/worker", home: "/d/agents/acme-pkg--worker/instances/src-1", work: { mode: "worktree", branch: "agents/src-1", head: "0123456789abcdef0123456789abcdef01234567" }, running: true },
  transcript: { included: true, complete: false, threads: [{ thread: "claude:abc", until: "t-9" }] },
  relation: { relation: "sibling", relativeTo: "src-1" },
  cloner: "acme-cloning-cloner-clone-src-1", requestedBy: "lead-1", createdAt: "2026-10-01T12:00:00.000Z",
};

const EXPECTED_PREAMBLE = `# Clone of src-1 — Port the teal theme to the settings page

\`\`\`oats-clone
{
  "version": 1,
  "source": {
    "instance": "src-1",
    "soul": "acme.pkg/worker",
    "home": "/d/agents/acme-pkg--worker/instances/src-1",
    "work": {
      "mode": "worktree",
      "branch": "agents/src-1",
      "head": "0123456789abcdef0123456789abcdef01234567"
    },
    "running": true
  },
  "transcript": {
    "included": true,
    "complete": false,
    "threads": [
      {
        "thread": "claude:abc",
        "until": "t-9"
      }
    ]
  },
  "relation": {
    "relation": "sibling",
    "relativeTo": "src-1"
  },
  "cloner": "acme-cloning-cloner-clone-src-1",
  "requestedBy": "lead-1",
  "createdAt": "2026-10-01T12:00:00.000Z"
}
\`\`\`

## You are a clone

You are a new, separate instance of acme.pkg/worker, with your own identity and alias (your instance name). You continue from src-1's situated understanding, written by a cloner in your brief. You are not src-1: never speak or sign as it. Its commitments, PRs, threads and children remain its own unless "Open threads and ownership" says they were handed to you. Items under "Working understanding" are provisional: verify them before you rely on them. Turn ids cite src-1's transcript as the cloner read it, from a temporary record that no longer exists: what matters is in the brief. Inherited material is not new evidence: put it in your own notes only after you re-verify it.

Read your brief first: \`.oats-attachments/clone-brief.md\`. It holds your goal and what the cloner carried over. It is private to this home (mode 0600): keep it there, and quote from it only what your work needs.
`;

test("the preamble is generated byte-identically from fixed inputs", () => {
  assert.equal(buildPreamble(PREAMBLE_INPUTS), EXPECTED_PREAMBLE);
  assert.equal(buildPreamble(structuredClone(PREAMBLE_INPUTS)), buildPreamble(PREAMBLE_INPUTS));
});

test("an excluded transcript is recorded as such in the provenance", () => {
  const text = buildPreamble({ ...PREAMBLE_INPUTS, transcript: { included: false } });
  assert.match(text, /"transcript": \{\n {4}"included": false,\n {4}"complete": null,\n {4}"threads": \[\]\n {2}\}/);
});

// Positive controls, built at runtime so the repository holds no token-shaped literals.
const CONTROLS = {
  "private-key": ["-----BEGIN " + "RSA PRIVATE KEY-----", "MIIEowIBAAKCAQEAx", "abc123", "-----END " + "RSA PRIVATE KEY-----"].join("\n"),
  "github-token": "gh" + "p_" + "A1b2C3d4".repeat(5),
  "github-pat": "github_" + "pat_" + "11ABCDEFG0" + "x".repeat(40),
  "anthropic-key": "sk-" + "ant-" + "api03-" + "a1B2".repeat(10),
  "sk-key": "sk-" + "proj-" + "Q".repeat(32),
  "aws-access-key-id": "AK" + "IA" + "IOSFODNN7EXAMPLE",
  "slack-token": "xo" + "xb-" + "1234567890-abcdefghijkl",
  "jwt": "ey" + "JhbGciOiJIUzI1NiJ9" + ".ey" + "JzdWIiOiIxMjM0NTY3ODkwIn0" + ".dozjgNryP4J3jVmNHl0w5N_XgL0n3I9PlFUP0THsR8U",
  "secret-assignment": "SERVICE_" + "TOKEN=" + "s3cr3tvalue99",
  "npm-token": "npm" + "_" + "a1B2c3D4e5".repeat(3) + "f6G7h8",
  "google-api-key": "AI" + "za" + "Sy" + "A1b2C3d4-_".repeat(3) + "e5f",
  "bearer-token": "Authorization: " + "Bea" + "rer " + "k7Qz9" + "Lm3Np".repeat(4),
  "url-credentials": "https://" + "deploy:" + "hunter2" + "pw" + "@git.example.com/repo.git",
};

test("every pattern has a positive control, and each is redacted by name without its value", () => {
  assert.deepEqual(Object.keys(CONTROLS).sort(), [...new Set(PATTERNS.map((p) => p.name))].sort());
  for (const [name, secret] of Object.entries(CONTROLS)) {
    const text = `line one\nthe value: ${secret} end\nline three`;
    const r = redact(text);
    assert.deepEqual(r.redactions, [{ line: 2, pattern: name }], name);
    assert.ok(r.text.includes(`[redacted:${name}]`), name);
    const value = name === "secret-assignment" ? "s3cr3tvalue99" : secret;
    assert.ok(!r.text.includes(value), `${name} value must not survive`);
    assert.equal(r.text.split("\n").length, text.split("\n").length, `${name} keeps line numbering`);
    assert.ok(!JSON.stringify(r.redactions).includes(value.slice(4, 12)));
  }
});

test("aweb's key file form (the ED25519 PEM block aw parses from .aw/signing.key) is redacted whole, LF or CRLF", () => {
  for (const eol of ["\n", "\r\n"]) {
    const key = ["-----BEGIN " + "ED25519 PRIVATE KEY-----", "Zm9v" + "QmFy".repeat(10), "-----END " + "ED25519 PRIVATE KEY-----"].join(eol);
    const text = `before\n${key}\nafter`;
    const r = redact(text);
    assert.deepEqual(r.redactions, [{ line: 2, pattern: "private-key" }], JSON.stringify(eol));
    assert.ok(!r.text.includes("QmFy") && !r.text.includes("PRIVATE KEY"), "neither the body nor the armour survives");
    assert.equal(r.text.split("\n").length, text.split("\n").length, "line numbering is kept");
  }
});

test("assignment forms: PASSWORD, *_API_KEY, quoted values; references are not values", () => {
  const r = redact(["PASSWORD: hunter22x", 'AWEB_API_KEY="aw_ab12cd34"', "TOKEN=$GITHUB_TOKEN", "API_KEY=<ask the human>", "MY_SECRET=[redacted:x]"].join("\n"));
  assert.deepEqual(r.redactions, [{ line: 1, pattern: "secret-assignment" }, { line: 2, pattern: "secret-assignment" }]);
  assert.match(r.text, /^PASSWORD: \[redacted:secret-assignment\]$/m);
  assert.match(r.text, /^AWEB_API_KEY="\[redacted:secret-assignment\]"$/m);
  assert.match(r.text, /^TOKEN=\$GITHUB_TOKEN$/m);
});

test("assignment forms in any case, with spaced separators, and as JSON or YAML keys; each reported once", () => {
  const v = "s3cr" + "etVal42";
  const cases = [
    [`password=${v}`, "password=[redacted:secret-assignment]"],
    [`secret: ${v}`, "secret: [redacted:secret-assignment]"],
    [`api_key = ${v}`, "api_key = [redacted:secret-assignment]"],
    [`client_secret=${v}`, "client_secret=[redacted:secret-assignment]"],
    [`Password :  ${v}`, "Password :  [redacted:secret-assignment]"],
    [`apiKey: ${v}`, "apiKey: [redacted:secret-assignment]"],
    [`x-api-key: ${v}`, "x-api-key: [redacted:secret-assignment]"],
    [`--password=${v}`, "--password=[redacted:secret-assignment]"],
    [`AWS_SECRET_ACCESS_KEY=${v}`, "AWS_SECRET_ACCESS_KEY=[redacted:secret-assignment]"],
    [`"PASSWORD": "${v}"`, '"PASSWORD": "[redacted:secret-assignment]"'],
    [`"api_key":"${v}"`, '"api_key":"[redacted:secret-assignment]"'],
    [`{"client_secret": "${v}", "id": "x"}`, '{"client_secret": "[redacted:secret-assignment]", "id": "x"}'],
    [`'token': '${v}'`, "'token': '[redacted:secret-assignment]'"],
    [`password: "${v}"`, 'password: "[redacted:secret-assignment]"'],
    // A quoted value runs to its closing quote (spaces and all), or to the end of the line.
    ['password: "correct horse battery"', 'password: "[redacted:secret-assignment]"'],
    [`password: "${v}`, 'password: "[redacted:secret-assignment]'],
    // ...to its REAL closing quote: a JSON \" or \\ and a YAML '' are part of the value.
    [String.raw`{"password":"\"` + v + '"}', '{"password":"[redacted:secret-assignment]"}'],
    [String.raw`{"password":"ab\\cd\"` + v + '","id":"x"}', '{"password":"[redacted:secret-assignment]","id":"x"}'],
    [`password: 'a''${v}'`, "password: '[redacted:secret-assignment]'"],
  ];
  for (const [text, expected] of cases) {
    const r = redact(text);
    assert.equal(r.text, expected);
    assert.deepEqual(r.redactions, [{ line: 1, pattern: "secret-assignment" }], text);
    assert.deepEqual(redact(r.text), { text: r.text, redactions: [] }, `redacting again changes nothing: ${text}`);
  }
});

test("near-misses of the assignment pattern stay untouched: prose, references, empty and no-value words", () => {
  const text = [
    "the password policy; the secret is out; passwords: many",
    "secret: none, password: null, token: true, api_key: n/a",
    "PASSWORD=$PASSWORD, password: <password>, secret=${SECRET}",
    'password=, password: ""',
    "tokens=5, password_policy: strict, secretary: Jane Doe, token_count: 12345",
  ].join("\n");
  const r = redact(text);
  assert.deepEqual(r.redactions, []);
  assert.equal(r.text, text);
});

test("an empty assignment never takes the next line: the next line's own assignment is found and reported there", () => {
  const v = "s3cr" + "etVal42";
  const r = redact(`password:\nAPI_KEY = ${v}\npassword=\nnext ordinary line`, { firstLine: 10 });
  assert.equal(r.text, "password:\nAPI_KEY = [redacted:secret-assignment]\npassword=\nnext ordinary line");
  assert.deepEqual(r.redactions, [{ line: 11, pattern: "secret-assignment" }]);
});

test("no-value words are an assignment's exemption only: an Authorization header's token is redacted whatever it reads", () => {
  for (const tok of ["unset", "true", "null"]) {
    const r = redact(`Authorization: Bearer ${tok}`);
    assert.equal(r.text, "Authorization: Bearer [redacted:bearer-token]");
    assert.deepEqual(r.redactions, [{ line: 1, pattern: "bearer-token" }]);
  }
});

test("npm, Google, Bearer and URL credentials: the forms that matter, each reported once", () => {
  const tok = "k7Qz9" + "Lm3Np".repeat(4);
  const npm = "npm" + "_" + "a1B2c3D4e5".repeat(3) + "f6G7h8";
  const jwt = "ey" + "JhbGciOiJIUzI1NiJ9" + ".ey" + "JzdWIiOiIxMjM0NTY3ODkwIn0" + ".dozjgNryP4J3jVmNHl0w5N_XgL0n3I9PlFUP0THsR8U";
  const cases = [
    [`curl -H "authorization: bearer ${tok}" https://api.example.com`, "bearer-token", `curl -H "authorization: bearer [redacted:bearer-token]" https://api.example.com`],
    [`send it as Bearer ${tok}== in the header`, "bearer-token", "send it as Bearer [redacted:bearer-token] in the header"],
    [`Authorization: Bearer ${jwt}`, "jwt", "Authorization: Bearer [redacted:jwt]"],
    [`NPM_TOKEN=${npm}`, "npm-token", "NPM_TOKEN=[redacted:npm-token]"],
    ["git remote add origin https://" + "x-access-token:" + tok + "@github.com/acme/repo.git", "url-credentials", "git remote add origin https://[redacted:url-credentials]@github.com/acme/repo.git"],
    ["postgres://" + "app:" + "s3cret" + "@db.internal:5432/main", "url-credentials", "postgres://[redacted:url-credentials]@db.internal:5432/main"],
    // An Authorization header is a credential whatever the token's length, digits or case.
    ["Authorization: Bearer " + "mF_9.B5f-4.1JqM", "bearer-token", "Authorization: Bearer [redacted:bearer-token]"],
    ["Authorization: Bearer " + "AbCdEfGhJkLmNpQrStUvWxYz".repeat(2), "bearer-token", "Authorization: Bearer [redacted:bearer-token]"],
    ["Authorization: BEARER " + tok, "bearer-token", "Authorization: BEARER [redacted:bearer-token]"],
    ['{"Authorization": "Bearer ' + "abc.def" + '"}', "bearer-token", '{"Authorization": "Bearer [redacted:bearer-token]"}'],
    // The password decides: a variable or masked username does not shield a literal password.
    ["https://$USER:" + "demo-pass-42" + "@db.example/main", "url-credentials", "https://[redacted:url-credentials]@db.example/main"],
    ["https://***:" + "demo-pass-42" + "@db.example/main", "url-credentials", "https://[redacted:url-credentials]@db.example/main"],
    // The userinfo runs to the last @ of the authority, raw or percent-encoded.
    ["https://app:" + "demo@pass42" + "@db.example/main", "url-credentials", "https://[redacted:url-credentials]@db.example/main"],
    ["https://app:" + "demo%40pass42" + "@db.example/main", "url-credentials", "https://[redacted:url-credentials]@db.example/main"],
    // ...but never past what bounds the URL: the host and the content around it stay.
    ['{"url":"https://app:' + "demo-pass-42" + '@db.example","owner":"ops@example.com"}', "url-credentials", '{"url":"https://[redacted:url-credentials]@db.example","owner":"ops@example.com"}'],
    ["[db](https://app:" + "demo-pass-42" + "@db.example),[owner](mailto:ops@example.com)", "url-credentials", "[db](https://[redacted:url-credentials]@db.example),[owner](mailto:ops@example.com)"],
    ["(https://app:" + "pw42" + "@db.example),(ops@example.com)", "url-credentials", "(https://[redacted:url-credentials]@db.example),(ops@example.com)"],
    ["x = 'https://app:" + "pw42" + "@db.example', o = 'ops@example.com'", "url-credentials", "x = 'https://[redacted:url-credentials]@db.example', o = 'ops@example.com'"],
    // A ${NAME} username is read whole; balanced parentheses inside a URL opened by ( are its own.
    ["https://${USER}:" + "demo-pass-42" + "@db.example/main", "url-credentials", "https://[redacted:url-credentials]@db.example/main"],
    ["[db](https://app:" + "demo@(part)42" + "@db.example)", "url-credentials", "[db](https://[redacted:url-credentials]@db.example)"],
    // A bracketed IP-literal host is a host.
    ["https://app:" + "demo-pass-42" + "@[::1]:8443/main", "url-credentials", "https://[redacted:url-credentials]@[::1]:8443/main"],
    ["postgres://app:" + "demo-pass-42" + "@[2001:db8::1]:5432/main", "url-credentials", "postgres://[redacted:url-credentials]@[2001:db8::1]:5432/main"],
    // A password may hold a raw / ? # (base64 does) or another character that ends an authority:
    // the userinfo runs on to the last @ before the URL's token ends, if a host follows it.
    ["git clone https://bob:" + "pa/ss" + "@github.com/x.git", "url-credentials", "git clone https://[redacted:url-credentials]@github.com/x.git"],
    ["https://bob:" + "p?ss" + "@host/x", "url-credentials", "https://[redacted:url-credentials]@host/x"],
    ["https://bob:" + "p#ss" + "@host/x", "url-credentials", "https://[redacted:url-credentials]@host/x"],
    ["https://bob:" + "p@ss/w" + "@host/x", "url-credentials", "https://[redacted:url-credentials]@host/x"],
    ["https://bob:" + "a^b|c\\d{e}[f]" + "@host/x", "url-credentials", "https://[redacted:url-credentials]@host/x"],
    ['{"url":"https://bob:' + "pa/ss" + '@db.example/x","owner":"ops@example.com"}', "url-credentials", '{"url":"https://[redacted:url-credentials]@db.example/x","owner":"ops@example.com"}'],
    ["[db](https://bob:" + "pa/ss" + "@db.example/x) ops@example.com", "url-credentials", "[db](https://[redacted:url-credentials]@db.example/x) ops@example.com"],
    ["https://bob:" + "pw42" + "@", "url-credentials", "https://[redacted:url-credentials]@"],
    // ...whatever script the host is written in.
    ["https://bob:" + "pa/ss" + "@例え.テスト/x", "url-credentials", "https://[redacted:url-credentials]@例え.テスト/x"],
    ["https://bob:" + "p?ss" + "@éxample.org/x", "url-credentials", "https://[redacted:url-credentials]@éxample.org/x"],
    ["https://bob:" + "p#ss" + "@💩.la/x", "url-credentials", "https://[redacted:url-credentials]@💩.la/x"],
    ["https://bob:" + "p@ss/w" + "@例え.テスト/x", "url-credentials", "https://[redacted:url-credentials]@例え.テスト/x"],
    // Pinned over-redaction: host:port/path@x cannot be told from user:digits/password@host,
    // so the path is redacted rather than risk the password.
    ["https://host:8080/x@y", "url-credentials", "https://[redacted:url-credentials]@y"],
    ["https://host.example:443/a@b", "url-credentials", "https://[redacted:url-credentials]@b"],
  ];
  for (const [text, pattern, expected] of cases) {
    const r = redact(text);
    assert.deepEqual(r.redactions, [{ line: 1, pattern }], text);
    assert.equal(r.text, expected);
    assert.deepEqual(redact(r.text), { text: r.text, redactions: [] }, `redacting again changes nothing: ${text}`);
  }
  // A comma-separated list: every URL is found. With no space between, the first userinfo may
  // run on to the last @ of the token (a password may hold a /), and the spans merge.
  const list = redact("https://app:" + "demo-one" + "@one.example, https://app:" + "demo-two" + "@two.example");
  assert.equal(list.text, "https://[redacted:url-credentials]@one.example, https://[redacted:url-credentials]@two.example");
  assert.deepEqual(list.redactions, [{ line: 1, pattern: "url-credentials" }, { line: 1, pattern: "url-credentials" }]);
  const joined = redact("https://app:" + "demo-one" + "@one.example,https://app:" + "demo-two" + "@two.example");
  assert.equal(joined.text, "https://[redacted:url-credentials]@two.example");
  assert.deepEqual(joined.redactions, [{ line: 1, pattern: "url-credentials" }]);
  const refs = redact("https://app:$ONE@one.example,https://app:" + "demo-two" + "@two.example");
  assert.equal(refs.text, "https://app:$ONE@one.example,https://[redacted:url-credentials]@two.example");
  // Overlapping userinfos merge into one span: the longer reading of the password wins.
  const merged = redact("(https://a:" + "b/x" + ",https://c:" + "d@e/f)g" + "@h");
  assert.equal(merged.text, "(https://[redacted:url-credentials]@h");
  assert.deepEqual(merged.redactions, [{ line: 1, pattern: "url-credentials" }]);
  assert.deepEqual(redact(merged.text), { text: merged.text, redactions: [] });
});

test("near-misses of the npm, Google, Bearer and URL patterns stay untouched", () => {
  const text = [
    "set npm_config_cache, or read npm_package_version; the npm_ prefix is npm's",
    "AIza is a prefix, AIzaSyShort is too short",
    "the bearer of bad news; Bearer tokens go in the Authorization header",
    "Bearer authentication-scheme-description, bearer 12 apples",
    "Authorization: Bearer $GITHUB_TOKEN and Authorization: Bearer <token>",
    "git@github.com:awebai/oats-cloning.git, https://user@host.example/x, ssh://git@host.example/repo",
    "mailto:someone@example.com, localhost:8080, http://localhost:8080/path",
    "https://host/a:b@c and https://user@host/a:b@c have a colon in the path, not in a userinfo",
    '"https://host:8080/x", "ops@example.com" and [link](https://host:8080/x) ops@example.com',
    "'https://host:8080/x' and 'ops@example.com', <https://host:8080/x>@example.com, `https://host:8080/x`@y",
    "https://$USER:$PASSWORD@host.example and https://app:$PASSWORD@db.example/main are references, not values",
    "https://app:@db.example has an empty password; https://user@host.example:8080/x has none",
    "https://${USER}:${PASSWORD}@db.example/main is a reference too",
    "https://[::1]:8080/x and https://user@[2001:db8::1]/y have no password",
    "(https://db.example:443),(ops@example.com) and (https://user@db.example:443),(ops@example.com) carry no credentials",
  ].join("\n");
  const r = redact(text);
  assert.deepEqual(r.redactions, []);
  assert.equal(r.text, text);
});

test("no false positives on SHAs, hex, UUIDs and ordinary prose", () => {
  const text = [
    "commit 0123456789abcdef0123456789abcdef01234567 on main",
    "sha256 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
    "uuid 157760ae-5d44-4438-83c7-6f71b2ecc9cf and 0xDEADBEEFCAFEBABE",
    "integrity sha256-23b857c603a0e0985782289a65a0248510544b3ca56d0251920eb4fcdd678d0e",
    "a task-force on risk-assessment used sk-learn; ghp is a prefix; AKIA alone",
    "did:key:z6MkhaXgBZDvotDkL5257faiztiGiC2QtKLGpbnnEGta2doK is public",
    "turn t-01J9ZQ3K5N8Y2W7V4X6M0P1R3S, tokens: 4096 per window",
  ].join("\n");
  const r = redact(text);
  assert.deepEqual(r.redactions, []);
  assert.equal(r.text, text);
});

test("a PEM block without its END line is redacted to the end, line numbers offset by firstLine", () => {
  const r = redact(["ok", "-----BEGIN " + "OPENSSH PRIVATE KEY-----", "b3BlbnNzaA", "more"].join("\n"), { firstLine: 40 });
  assert.deepEqual(r.redactions, [{ line: 41, pattern: "private-key" }]);
  assert.ok(!r.text.includes("b3BlbnNzaA"));
});
