import { fail } from "./errors.mjs";

// The clone's brief: the cloner's body (spec §6.3 headings), the generated
// preamble, and the mechanical redaction pass (R2a) over both.

export const HEADINGS = [
  "Your goal",
  "What is verified",
  "Decisions and why",
  "Working understanding (provisional)",
  "Open threads and ownership",
  "Work state",
  "Where to look",
  "Not carried",
];

/** Where the brief lives in the clone's home (R2b): a private attachment. */
export const BRIEF_NAME = "clone-brief.md";
export const BRIEF_PATH = `.oats-attachments/${BRIEF_NAME}`;

/** Check the body's structure. `goal` must appear verbatim under "Your goal". */
export function checkBrief(text, { goal } = {}) {
  const bad = (why, details) => fail("E_CLONE_BRIEF", `brief: ${why}`, details);
  const lines = text.split("\n");
  const sections = [];
  let fence = null;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const f = /^\s{0,3}(`{3,}|~{3,})(.*)$/.exec(line);
    if (f) {
      if (fence === null) {
        if (/^oats-clone/.test(f[2].trim())) bad(`line ${i + 1}: an oats-clone block is generated by the command, never written in the brief`);
        fence = f[1][0];
      } else if (f[1][0] === fence && !f[2].trim()) fence = null;
      if (sections.length) sections.at(-1).content.push(line);
      continue;
    }
    if (fence === null) {
      if (/^#\s/.test(line)) bad(`line ${i + 1}: no level-1 heading; the preamble supplies the title`);
      const h = /^##\s+(.*?)\s*#*\s*$/.exec(line);
      if (h) { sections.push({ heading: h[1], line: i + 1, content: [] }); continue; }
    }
    if (!sections.length) {
      if (line.trim()) bad(`line ${i + 1}: the brief starts with "## ${HEADINGS[0]}"`);
      continue;
    }
    sections.at(-1).content.push(line);
  }
  if (fence !== null) bad("an unterminated code fence");
  const names = sections.map((s) => s.heading);
  const extra = names.filter((n) => !HEADINGS.includes(n));
  if (extra.length) bad(`unknown heading(s): ${extra.map((n) => `"## ${n}"`).join(", ")}; use exactly the ${HEADINGS.length} headings, in order (### subheadings are fine)`);
  if (names.length !== HEADINGS.length || names.some((n, i) => n !== HEADINGS[i])) {
    bad(`the headings must be, in this order: ${HEADINGS.map((h) => `"## ${h}"`).join(", ")}`, { found: names });
  }
  for (const s of sections) {
    if (!s.content.some((l) => l.trim())) bad(`"## ${s.heading}" is empty: write "None."`);
  }
  if (typeof goal === "string" && !sections[0].content.join("\n").includes(goal.trim())) {
    bad('"## Your goal" must hold the request\'s goal verbatim');
  }
  return true;
}

const firstLine = (text) => (text.split("\n").map((l) => l.trim()).find(Boolean) ?? "");

/** The generated preamble (spec §6.3 + R2b). Deterministic: the same inputs
 *  give the same bytes. It becomes the clone's TASK.md task and the head of the
 *  attached brief. */
export function buildPreamble(p) {
  const title = firstLine(p.goal);
  const shortTitle = title.length > 120 ? `${title.slice(0, 119)}…` : title;
  const provenance = {
    version: 1,
    source: {
      instance: p.source.instance,
      soul: p.source.soul,
      home: p.source.home,
      work: { mode: p.source.work.mode ?? null, branch: p.source.work.branch ?? null, head: p.source.work.head ?? null },
      running: p.source.running === true,
    },
    transcript: {
      included: p.transcript.included === true,
      complete: p.transcript.included === true ? p.transcript.complete === true : null,
      threads: p.transcript.included === true ? p.transcript.threads.map((t) => ({ thread: t.thread, until: t.until })) : [],
    },
    relation: { relation: p.relation.relation, relativeTo: p.relation.relativeTo ?? null },
    cloner: p.cloner,
    requestedBy: p.requestedBy,
    createdAt: p.createdAt,
  };
  const s = p.source.instance, soul = p.source.soul;
  return [
    `# Clone of ${s} — ${shortTitle}`,
    "",
    "```oats-clone",
    JSON.stringify(provenance, null, 2),
    "```",
    "",
    "## You are a clone",
    "",
    `You are a new, separate instance of ${soul}, with your own identity and alias (your instance name). ` +
      `You continue from ${s}'s situated understanding, written by a cloner in your brief. ` +
      `You are not ${s}: never speak or sign as it. ` +
      `Its commitments, PRs, threads and children remain its own unless "Open threads and ownership" says they were handed to you. ` +
      `Items under "Working understanding" are provisional: verify them before you rely on them. ` +
      `Turn ids cite ${s}'s transcript as the cloner read it, from a temporary record that no longer exists: what matters is in the brief. ` +
      "Inherited material is not new evidence: put it in your own notes only after you re-verify it.",
    "",
    `Read your brief first: \`${BRIEF_PATH}\`. It holds your goal and what the cloner carried over. ` +
      "It is private to this home (mode 0600): keep it there, and quote from it only what your work needs.",
    "",
  ].join("\n");
}

const isReference = (v) => /^(?:\$|<|\[redacted|\*{3,}|x{3,}$)/i.test(v);

const URL_SCHEME = /\b[a-z][a-z0-9+.-]*:\/\//gi;
// What ends a URL's authority: whitespace, the starts of path, query and
// fragment, and what RFC 3986 never allows raw there ([ and ] only around an
// IP-literal host, which the scanner reads whole).
const URL_STOP = /[\s/?#"<>`{}|\\^[\]]/;
// RFC 3986 IP-literal contents: IPv6 (with an optional %25 zone) or IPvFuture.
const IP_LITERAL = /^(?:[0-9A-Fa-f:.]+(?:%25[0-9A-Za-z._~-]+)?|v[0-9A-Fa-f]+\.[0-9A-Za-z._~!$&'()*+,;=:-]+)$/;

/** Credentials in URLs (scheme://user:password@host), one URL at a time.
 *  Each URL's authority is bounded once: at a URL_STOP character, at the
 *  closing ' of a URL opened by ', and at the ) that closes a URL opened by (
 *  (balanced inner parentheses are part of it). A ${NAME} and a bracketed
 *  IP-literal host ([::1]) are read whole. The
 *  userinfo then runs to the last @ of that authority (a raw @ in a password is
 *  still password), and the password alone decides: $USER:literal is
 *  redacted, app:$PASSWORD is a reference. The whole userinfo is replaced;
 *  the scheme and host stay. Without a password nothing is replaced. A URL
 *  with no opener that runs into other text with no whitespace between can
 *  take that text as userinfo: it errs toward redacting, never toward a leak. */
function urlCredentials(text) {
  const spans = [];
  URL_SCHEME.lastIndex = 0;
  for (let m; (m = URL_SCHEME.exec(text)); ) {
    const start = m.index + m[0].length, opener = text[m.index - 1];
    let end = start, depth = 0;
    while (end < text.length) {
      const c = text[end];
      if (c === "$" && text[end + 1] === "{") {
        const close = text.indexOf("}", end + 2);
        if (close !== -1 && /^[A-Za-z_][A-Za-z0-9_]*$/.test(text.slice(end + 2, close))) { end = close + 1; continue; }
      }
      if (c === "[" && (end === start || text[end - 1] === "@")) {
        const close = text.indexOf("]", end + 1);
        if (close !== -1 && IP_LITERAL.test(text.slice(end + 1, close))) { end = close + 1; continue; }
      }
      if (URL_STOP.test(c) || (opener === "'" && c === "'")) break;
      if (c === "(") depth++;
      else if (c === ")") { if (depth === 0 && opener === "(") break; depth = Math.max(0, depth - 1); }
      end++;
    }
    // exec() resumes right after this scheme: a scheme inside this URL's
    // bounds (a comma-separated list) is still found. A '/' ends the
    // authority, so the next URL's userinfo is never inside this one's.
    const authority = text.slice(start, end), at = authority.lastIndexOf("@");
    if (at < 1 || at === authority.length - 1) continue;
    const userinfo = authority.slice(0, at), colon = userinfo.indexOf(":");
    if (colon === -1) continue;
    const password = userinfo.slice(colon + 1);
    if (password && !isReference(password) && !(spans.length && start < spans.at(-1).end)) spans.push({ start, end: start + at });
  }
  return spans;
}

/** Secret patterns (spec §5.3). A seatbelt, not the policy: /plan-clone's
 *  exclusions decide what a brief carries; this catches what slips through. */
export const PATTERNS = [
  { name: "private-key", re: /-----BEGIN (?:[A-Z0-9]+ )*PRIVATE KEY(?: BLOCK)?-----(?:[\s\S]*?-----END (?:[A-Z0-9]+ )*PRIVATE KEY(?: BLOCK)?-----|[\s\S]*$)/g },
  { name: "github-token", re: /\bgh[pousr]_[A-Za-z0-9]{30,}/g },
  { name: "github-pat", re: /\bgithub_pat_[A-Za-z0-9_]{22,}/g },
  { name: "anthropic-key", re: /\bsk-ant-[A-Za-z0-9_-]{20,}/g },
  { name: "sk-key", re: /\bsk-(?!ant-)[A-Za-z0-9_-]{20,}/g },
  { name: "aws-access-key-id", re: /\b(?:AKIA|ASIA|ABIA|ACCA|AGPA|AIDA|AIPA|ANPA|ANVA|APKA|AROA)[A-Z0-9]{16}\b/g },
  { name: "slack-token", re: /\bxox[abprs]-[A-Za-z0-9-]{10,}/g },
  { name: "jwt", re: /\beyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}/g },
  { name: "npm-token", re: /\bnpm_[A-Za-z0-9]{36}(?![A-Za-z0-9])/g },
  { name: "google-api-key", re: /\bAIza[0-9A-Za-z_-]{35}(?![0-9A-Za-z_-])/g },
  // Bearer tokens; only the token is replaced. In an Authorization header any
  // RFC 6750 token is one, whatever its length or case. Bare "Bearer <x>" in
  // prose must look like a token (20+ characters with a digit), so "the bearer
  // of" never matches. References ($TOKEN, <token>) are never values.
  { name: "bearer-token", re: /\b(Authorization["']?\s*:\s*["']?Bearer)(\s+)()([A-Za-z0-9._~+/-]+=*)(?![A-Za-z0-9._~+/=-])/gi, value: true },
  { name: "bearer-token", re: /\b(bearer)(\s+)()((?=[A-Za-z0-9._~+/-]*\d)[A-Za-z0-9._~+/-]{20,}=*)(?![A-Za-z0-9._~+/=-])/gi, value: true },
  { name: "url-credentials", spans: urlCredentials },
  // NAME=value / NAME: value for credential-shaped names. Only the value is
  // replaced; a reference ($VAR, <placeholder>) is not a value.
  { name: "secret-assignment", re: /\b((?:[A-Z][A-Z0-9_]*_)?(?:API_KEY|TOKEN|SECRET|SECRET_ACCESS_KEY|PASSWORD|PASSWD|PRIVATE_KEY))(\s*[:=]\s*)(["']?)([^\s"'`]{4,})/g, value: true },
];

const lineAt = (text, offset) => {
  let n = 1;
  for (let i = text.indexOf("\n"); i !== -1 && i < offset; i = text.indexOf("\n", i + 1)) n++;
  return n;
};

/** Replace every match with [redacted:<pattern>]. Line numbers refer to the
 *  input text (a multi-line match keeps its line count), offset by `firstLine - 1`.
 *  Never returns the matched values. */
export function redact(text, { firstLine = 1 } = {}) {
  let out = text;
  const redactions = [];
  for (const { name, re, value, spans } of PATTERNS) {
    if (spans) {
      // Single-line spans, replaced last to first so offsets stay valid.
      const found = spans(out);
      for (const { start } of found) redactions.push({ line: lineAt(out, start) + firstLine - 1, pattern: name });
      for (const { start, end } of found.reverse()) out = `${out.slice(0, start)}[redacted:${name}]${out.slice(end)}`;
      continue;
    }
    out = out.replace(re, (...m) => {
      const offset = m.at(-2);
      const match = m[0];
      if (value) {
        const [, key, sep, quote, val] = m;
        if (isReference(val)) return match;
        redactions.push({ line: lineAt(out, offset) + firstLine - 1, pattern: name });
        return `${key}${sep}${quote}[redacted:${name}]`;
      }
      redactions.push({ line: lineAt(out, offset) + firstLine - 1, pattern: name });
      return `[redacted:${name}]` + "\n".repeat((match.match(/\n/g) || []).length);
    });
  }
  redactions.sort((a, b) => a.line - b.line || a.pattern.localeCompare(b.pattern));
  return { text: out, redactions };
}
